In [1]:
import numpy as np

In [8]:
# arr = np.array([1,2,3,4,5,6])
arr = np.array([[1,2,3,4,5,6],
               [1,2,3,4,5,6]])

In [17]:
arr.shape

(2, 6)

In [18]:
arr

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [26]:
a = np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
a = np.zeros([4])
a

array([0., 0., 0., 0.])

In [35]:
a = np.full((8,4),4)
a

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [38]:
e = np.random.random((5,4))

In [42]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,2],[3,4]])

In [43]:
x+y

array([[2, 4],
       [6, 8]])

In [44]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)],
             dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], 
              [(3,2,1), (4,5,6)]],
             dtype = float)

In [50]:
x.dot(y)
np.dot(x,y)

array([[ 7, 10],
       [15, 22]])

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])