In [2]:
import numpy as np

In [3]:
# arr = np.array([1,2,3,4,5,6])
arr = np.array([[1,2,3,4,5,6],
               [1,2,3,4,5,6]])

In [4]:
arr.shape

(2, 6)

In [21]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
np.random.rand(1,5)

array([[0.57352475, 0.45563472, 0.57716755, 0.39184709, 0.38505001]])

In [5]:
arr

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [14]:
a = np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
a = np.zeros([4])
a

array([0., 0., 0., 0.])

In [15]:
a = np.full((8,4),5)
a

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [9]:
e = np.random.random((5,4))

In [10]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,2],[3,4]])

In [11]:
x+y

array([[2, 4],
       [6, 8]])

In [12]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)],
             dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], 
              [(3,2,1), (4,5,6)]],
             dtype = float)

In [13]:
x.dot(y)
np.dot(x,y)

array([[ 7, 10],
       [15, 22]])